/**
 * Report exporters — download the chat audit faithfully (MD / Word / PDF).
 * Prefer full chat content so Active / Paused / campaigns / risks are not lost.
 * Every export is polished + quality-checked before the file is returned.
 */

import { sanitizeReportText } from "@/lib/reports/parse-markdown";
import { exportBrandedPdf } from "@/lib/reports/pdf";
import {
  polishReportForExport,
  type ReportQualityResult,
} from "@/lib/reports/quality";
import { renderReportHtml } from "@/lib/reports/template";
import { inferExportTitle } from "@/lib/reports/prepare-export";
import { looksLikeFullAuditMarkdown } from "@/lib/report/from-markdown";

export type ReportFormat = "md" | "docx" | "pdf";

export { resolveExportAuditReport } from "@/lib/reports/export-resolve";
export {
  polishReportForExport,
  verifyReportQuality,
  deglueReportProse,
  splitGluedToken,
} from "@/lib/reports/quality";

function slugify(title: string): string {
  return (
    sanitizeReportText(title)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 48) || "adspirer-report"
  );
}

export function buildReportFilename(
  title: string,
  format: ReportFormat,
): string {
  const base = slugify(title);
  if (format === "md") return `${base}.md`;
  if (format === "docx") return `${base}.doc`;
  return `${base}.pdf`;
}

function polishBody(title: string, body: string) {
  const polished = polishReportForExport(body, title);
  const docTitle = inferExportTitle(polished.markdown, title);
  return { ...polished, docTitle };
}

/** Clean markdown download — preserves full audit body. */
export function exportMarkdown(title: string, body: string): string {
  const { markdown, docTitle } = polishBody(title, body);
  if (/^#\s+/m.test(markdown)) return markdown;
  return `# ${sanitizeReportText(docTitle)}\n\n${markdown}`;
}

/** Word HTML from the full cleaned audit body. */
export function exportWordHtml(title: string, body: string): string {
  const { markdown, docTitle } = polishBody(title, body);
  return renderReportHtml({
    title: docTitle,
    markdown,
    subtitle: looksLikeFullAuditMarkdown(body)
      ? "Full Meta Ads audit · Generated by Adspirer AI"
      : "Meta Ads operator report · Generated by Adspirer AI",
  });
}

export function exportSimplePdf(title: string, body: string): Uint8Array {
  const { markdown, docTitle } = polishBody(title, body);
  return exportBrandedPdf(docTitle, markdown);
}

/**
 * Always export from the chat/content body so details match what the operator saw.
 * Polishes + verifies before returning bytes.
 */
export async function exportReportPayload(input: {
  format: ReportFormat;
  title: string;
  content: string;
  report?: unknown;
}): Promise<{
  body: Uint8Array | string;
  filename: string;
  contentType: string;
  quality: ReportQualityResult;
  polishPasses: number;
}> {
  const polished = polishReportForExport(input.content, input.title);
  const docTitle = inferExportTitle(polished.markdown, input.title);
  const filename = buildReportFilename(docTitle, input.format);

  if (input.format === "md") {
    const body = /^#\s+/m.test(polished.markdown)
      ? polished.markdown
      : `# ${sanitizeReportText(docTitle)}\n\n${polished.markdown}`;
    return {
      body,
      filename,
      contentType: "text/markdown; charset=utf-8",
      quality: polished.quality,
      polishPasses: polished.passes,
    };
  }
  if (input.format === "docx") {
    return {
      body: renderReportHtml({
        title: docTitle,
        markdown: polished.markdown,
        subtitle: looksLikeFullAuditMarkdown(input.content)
          ? "Full Meta Ads audit · Generated by Adspirer AI"
          : "Meta Ads operator report · Generated by Adspirer AI",
      }),
      filename,
      contentType: "application/msword; charset=utf-8",
      quality: polished.quality,
      polishPasses: polished.passes,
    };
  }
  return {
    body: exportBrandedPdf(docTitle, polished.markdown),
    filename,
    contentType: "application/pdf",
    quality: polished.quality,
    polishPasses: polished.passes,
  };
}
