/**
 * Report exporters — download the chat audit faithfully (MD / Word / PDF / Excel).
 * Prefer full chat content so Active / Paused / campaigns / risks are not lost.
 * Every export is polished + quality-checked before the file is returned.
 */

import { sanitizeReportText } from "@/lib/reports/parse-markdown";
import { renderReportDocx } from "@/lib/reports/docx-document";
import { renderReportPdf } from "@/lib/reports/pdf-document";
import { renderReportXlsx } from "@/lib/reports/xlsx-document";
import {
  polishReportForExport,
  type ReportQualityResult,
} from "@/lib/reports/quality";
import { renderReportHtml } from "@/lib/reports/template";
import { inferExportTitle } from "@/lib/reports/prepare-export";
import { looksLikeFullAuditMarkdown } from "@/lib/report/from-markdown";

export type ReportFormat = "md" | "docx" | "pdf" | "xlsx";

export const REPORT_CONTENT_TYPES: Record<ReportFormat, string> = {
  md: "text/markdown; charset=utf-8",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  pdf: "application/pdf",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
};

export { resolveExportAuditReport } from "@/lib/reports/export-resolve";
export {
  polishReportForExport,
  verifyReportQuality,
  deglueReportProse,
  splitGluedToken,
} from "@/lib/reports/quality";

function slugify(title: string): string {
  return (
    sanitizeReportText(title)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 48) || "spendsmith-report"
  );
}

export function buildReportFilename(
  title: string,
  format: ReportFormat,
): string {
  return `${slugify(title)}.${format}`;
}

function polishBody(title: string, body: string) {
  const polished = polishReportForExport(body, title);
  const docTitle = inferExportTitle(polished.markdown, title);
  return { ...polished, docTitle };
}

function reportSubtitle(body: string): string {
  return looksLikeFullAuditMarkdown(body)
    ? "Full Meta Ads audit · Generated by Spendsmith"
    : "Meta Ads report · Generated by Spendsmith";
}

/** Clean markdown download — preserves full audit body. */
export function exportMarkdown(title: string, body: string): string {
  const { markdown, docTitle } = polishBody(title, body);
  if (/^#\s+/m.test(markdown)) return markdown;
  return `# ${sanitizeReportText(docTitle)}\n\n${markdown}`;
}

/** Branded HTML (used for previews) from the full cleaned audit body. */
export function exportWordHtml(title: string, body: string): string {
  const { markdown, docTitle } = polishBody(title, body);
  return renderReportHtml({ title: docTitle, markdown, subtitle: reportSubtitle(body) });
}

/** Native Word document (.docx) from the full cleaned audit body. */
export async function exportDocx(title: string, body: string): Promise<Uint8Array> {
  const { markdown, docTitle } = polishBody(title, body);
  return renderReportDocx({ title: docTitle, markdown, subtitle: reportSubtitle(body) });
}

/** Branded PDF from the full cleaned audit body (typeset with embedded Inter). */
export async function exportPdf(title: string, body: string): Promise<Uint8Array> {
  const { markdown, docTitle } = polishBody(title, body);
  return renderReportPdf({ title: docTitle, markdown, subtitle: reportSubtitle(body) });
}

/** Excel workbook: narrative sheet + one sheet per table with real numbers. */
export function exportXlsx(title: string, body: string): Uint8Array {
  const { markdown, docTitle } = polishBody(title, body);
  return renderReportXlsx({ title: docTitle, markdown });
}

/**
 * Always export from the chat/content body so details match what the operator saw.
 * Polishes + verifies before returning bytes.
 */
export async function exportReportPayload(input: {
  format: ReportFormat;
  title: string;
  content: string;
  report?: unknown;
}): Promise<{
  body: Uint8Array | string;
  filename: string;
  contentType: string;
  quality: ReportQualityResult;
  polishPasses: number;
}> {
  const polished = polishReportForExport(input.content, input.title);
  const docTitle = inferExportTitle(polished.markdown, input.title);
  const doc = {
    title: docTitle,
    markdown: polished.markdown,
    subtitle: reportSubtitle(input.content),
  };

  let body: Uint8Array | string;
  switch (input.format) {
    case "md":
      body = /^#\s+/m.test(polished.markdown)
        ? polished.markdown
        : `# ${sanitizeReportText(docTitle)}\n\n${polished.markdown}`;
      break;
    case "docx":
      body = await renderReportDocx(doc);
      break;
    case "xlsx":
      body = renderReportXlsx(doc);
      break;
    default:
      body = await renderReportPdf(doc);
  }
  return {
    body,
    filename: buildReportFilename(docTitle, input.format),
    contentType: REPORT_CONTENT_TYPES[input.format],
    quality: polished.quality,
    polishPasses: polished.passes,
  };
}
