import {
  type InlineSpan,
  type ReportBlock,
  parseMarkdownToBlocks,
  sanitizeReportText,
} from "@/lib/reports/parse-markdown";

/** Adspirer report brand tokens — teal / slate professional. */
export const REPORT_THEME = {
  primary: "#0F766E",
  primaryDark: "#115E59",
  primaryLight: "#CCFBF1",
  ink: "#0F172A",
  muted: "#64748B",
  border: "#E2E8F0",
  surface: "#F8FAFC",
  tableHeader: "#F0FDFA",
  white: "#FFFFFF",
  accent: "#14B8A6",
} as const;

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderSpansHtml(spans: InlineSpan[]): string {
  const parts: string[] = [];
  for (let i = 0; i < spans.length; i += 1) {
    const span = spans[i];
    const t = escapeHtml(span.text);
    let html = t;
    if (span.type === "bold") html = `<strong>${t}</strong>`;
    else if (span.type === "italic") html = `<em>${t}</em>`;
    else if (span.type === "code") {
      html = `<code style="background:${REPORT_THEME.surface};padding:1px 4px;border-radius:3px;font-size:10pt;">${t}</code>`;
    }
    if (parts.length) {
      const prev = spans[i - 1]?.text ?? "";
      const needsSpace =
        /[A-Za-z0-9)]$/.test(prev) &&
        /^[A-Za-z0-9(]/.test(span.text) &&
        !/\s$/.test(prev) &&
        !/^\s/.test(span.text);
      if (needsSpace) parts.push(" ");
    }
    parts.push(html);
  }
  return parts.join("");
}

function renderBlocksHtml(blocks: ReportBlock[]): string {
  return blocks
    .map((block) => {
      switch (block.type) {
        case "heading": {
          const tag = `h${block.level}` as "h1" | "h2" | "h3";
          return `<${tag}>${escapeHtml(block.text)}</${tag}>`;
        }
        case "paragraph":
          return `<p>${renderSpansHtml(block.spans)}</p>`;
        case "list": {
          const tag = block.ordered ? "ol" : "ul";
          const items = block.items
            .map((item) => `<li>${renderSpansHtml(item)}</li>`)
            .join("");
          return `<${tag}>${items}</${tag}>`;
        }
        case "table": {
          const head = block.headers
            .map((h) => `<th>${escapeHtml(h)}</th>`)
            .join("");
          const body = block.rows
            .map(
              (row) =>
                `<tr>${row.map((c) => `<td>${escapeHtml(c)}</td>`).join("")}</tr>`,
            )
            .join("");
          return `<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
        }
        case "hr":
          return `<hr />`;
        default:
          return "";
      }
    })
    .join("\n");
}

export function renderReportHtml(input: {
  title: string;
  markdown: string;
  subtitle?: string;
  generatedAt?: Date;
}): string {
  const title = sanitizeReportText(input.title);
  const generatedAt = input.generatedAt ?? new Date();
  const dateLabel = generatedAt.toLocaleString("en-AU", {
    dateStyle: "medium",
    timeStyle: "short",
  });
  const subtitle =
    input.subtitle?.trim() ||
    "Meta Ads operator report · Generated by Adspirer AI";

  let blocks = parseMarkdownToBlocks(input.markdown);
  // Drop duplicate H1 if it matches the document title
  if (
    blocks[0]?.type === "heading" &&
    blocks[0].level === 1 &&
    blocks[0].text.toLowerCase() === title.toLowerCase()
  ) {
    blocks = blocks.slice(1);
  }

  const body = renderBlocksHtml(blocks);
  const t = REPORT_THEME;

  return `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)}</title>
<!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View><w:Zoom>100</w:Zoom></w:WordDocument></xml><![endif]-->
<style>
  @page { margin: 1.6cm 1.8cm; }
  body {
    font-family: Calibri, "Segoe UI", Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.55;
    color: ${t.ink};
    margin: 0;
    padding: 0;
  }
  .cover {
    background: ${t.primary};
    color: ${t.white};
    padding: 28px 32px 24px;
    margin: 0 0 28px 0;
  }
  .cover .brand {
    font-size: 10pt;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    opacity: 0.9;
    font-weight: 600;
    margin: 0 0 10px 0;
  }
  .cover h1 {
    font-size: 22pt;
    margin: 0 0 8px 0;
    font-weight: 700;
    line-height: 1.25;
    color: ${t.white};
    border: none;
    padding: 0;
  }
  .cover .meta {
    font-size: 10pt;
    opacity: 0.92;
    margin: 0;
  }
  .content { padding: 0 8px 24px; }
  h1 {
    font-size: 18pt;
    color: ${t.primaryDark};
    margin: 22px 0 10px;
    padding-bottom: 6px;
    border-bottom: 2px solid ${t.primaryLight};
  }
  h2 {
    font-size: 14pt;
    color: ${t.primary};
    margin: 20px 0 8px;
    padding-bottom: 4px;
    border-bottom: 1px solid ${t.border};
  }
  h3 {
    font-size: 12pt;
    color: ${t.ink};
    margin: 16px 0 6px;
  }
  p { margin: 0 0 10px 0; text-align: left; }
  ul, ol { margin: 0 0 12px 1.2em; padding: 0; text-align: left; }
  li { margin: 0 0 6px 0; text-align: left; line-height: 1.5; }
  strong { color: ${t.ink}; }
  td, th { text-align: left; }
  hr {
    border: none;
    border-top: 1px solid ${t.border};
    margin: 18px 0;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 10px 0 16px;
    font-size: 10pt;
  }
  th {
    background: ${t.tableHeader};
    color: ${t.primaryDark};
    text-align: left;
    padding: 8px 10px;
    border: 1px solid ${t.border};
    font-weight: 700;
  }
  td {
    padding: 7px 10px;
    border: 1px solid ${t.border};
    vertical-align: top;
  }
  tr:nth-child(even) td { background: ${t.surface}; }
  .footer {
    margin-top: 32px;
    padding-top: 12px;
    border-top: 2px solid ${t.primary};
    font-size: 9pt;
    color: ${t.muted};
  }
</style>
</head>
<body>
  <div class="cover">
    <p class="brand">Adspirer AI</p>
    <h1>${escapeHtml(title)}</h1>
    <p class="meta">${escapeHtml(subtitle)} · ${escapeHtml(dateLabel)}</p>
  </div>
  <div class="content">
    ${body}
    <div class="footer">
      Confidential — for internal operator use. Generated ${escapeHtml(dateLabel)}.
    </div>
  </div>
</body>
</html>`;
}
