import { StyleSheet } from "@react-pdf/renderer";
import { C, T, S, PAGE, R } from "@/lib/report/theme";

export const s = StyleSheet.create({
  page: {
    paddingTop: PAGE.margin,
    paddingHorizontal: PAGE.margin,
    paddingBottom: PAGE.margin + PAGE.footerH,
    fontFamily: "Inter",
    fontSize: T.body,
    lineHeight: T.lhBody,
    color: C.ink900,
    backgroundColor: C.paper,
    textAlign: "left",
  },
  pageLead: { paddingTop: 0 },

  masthead: {
    marginHorizontal: -PAGE.margin,
    marginBottom: S[6],
    paddingHorizontal: PAGE.margin,
    paddingTop: S[6],
    paddingBottom: S[5],
    backgroundColor: C.teal900,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  logoTile: {
    width: 16,
    height: 16,
    borderRadius: R.sm,
    backgroundColor: C.teal400,
    color: C.teal900,
    fontSize: 9,
    fontWeight: 700,
    textAlign: "center",
    paddingTop: 2,
  },
  wordmark: {
    fontSize: T.micro,
    fontWeight: 700,
    letterSpacing: 1.1,
    color: C.teal100,
  },
  h1: {
    fontSize: T.h1,
    fontWeight: 600,
    color: C.paper,
    letterSpacing: -0.35,
    lineHeight: 1.14,
  },
  subtitle: {
    fontSize: T.small + 0.5,
    color: C.teal100,
    marginTop: S[1],
  },

  eyebrow: {
    fontSize: T.micro,
    fontWeight: 700,
    letterSpacing: 1,
    color: C.teal700,
    textTransform: "uppercase",
  },
  h2: {
    fontSize: T.h2,
    fontWeight: 600,
    color: C.teal900,
    marginTop: 3,
    letterSpacing: -0.15,
  },
  secRule: {
    width: 26,
    height: 2,
    backgroundColor: C.teal700,
    marginTop: S[2],
  },

  kpiRow: {
    flexDirection: "row",
    gap: S[2],
    marginBottom: S[5],
  },
  kpi: {
    flex: 1,
    borderWidth: 1,
    borderColor: C.hair,
    borderRadius: R.lg,
    backgroundColor: C.paper2,
    padding: S[2] + 2,
  },
  kpiLbl: {
    fontSize: T.micro,
    fontWeight: 600,
    letterSpacing: 0.8,
    color: C.teal700,
    textTransform: "uppercase",
  },
  kpiVal: {
    fontSize: T.kpi,
    fontWeight: 600,
    marginTop: S[1] + 1,
    letterSpacing: -0.3,
  },
  kpiNote: {
    fontSize: T.micro,
    color: C.ink500,
    marginTop: 3,
    lineHeight: 1.35,
  },
  kpiFlag: {
    backgroundColor: C.medBg,
    borderColor: C.medBorder,
  },

  callout: {
    borderLeftWidth: 3,
    borderLeftColor: C.teal400,
    backgroundColor: C.teal50,
    padding: S[3],
    borderTopRightRadius: R.md,
    borderBottomRightRadius: R.md,
    marginBottom: S[5],
  },
  calloutLbl: {
    fontSize: T.micro,
    fontWeight: 700,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: C.teal700,
    marginBottom: S[1],
  },

  defRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: C.hair,
    paddingVertical: S[2] - 1,
  },
  defLbl: {
    width: "34%",
    fontSize: T.micro,
    fontWeight: 600,
    letterSpacing: 0.6,
    color: C.ink500,
    textTransform: "uppercase",
  },
  defVal: { flex: 1, fontSize: T.body },
  mono: {
    fontFamily: "JetBrainsMono",
    fontSize: T.mono,
    color: C.ink700,
  },

  card: {
    borderWidth: 1,
    borderColor: C.hair,
    borderRadius: R.lg,
    marginBottom: S[3],
  },
  cardHd: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: C.paper2,
    padding: S[3],
    borderBottomWidth: 1,
    borderBottomColor: C.hair,
    borderTopLeftRadius: R.lg,
    borderTopRightRadius: R.lg,
  },
  cardBd: {
    paddingHorizontal: S[3],
    paddingBottom: S[3],
  },

  pill: {
    fontSize: 5.5,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    paddingVertical: 2.5,
    paddingHorizontal: 6,
    borderRadius: R.pill,
    borderWidth: 1,
  },
  sev: {
    fontSize: 5.5,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    paddingVertical: 2.5,
    paddingHorizontal: 6,
    borderRadius: R.sm,
  },
  chip: {
    fontSize: 7,
    fontWeight: 500,
    color: C.teal800,
    backgroundColor: C.teal50,
    borderWidth: 1,
    borderColor: C.teal100,
    borderRadius: R.sm,
    paddingVertical: 2,
    paddingHorizontal: 6,
    marginRight: 4,
    marginBottom: 4,
  },

  sublbl: {
    fontSize: T.micro,
    fontWeight: 700,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: C.ink500,
    marginTop: S[3],
    marginBottom: S[2],
  },
  bullet: {
    flexDirection: "row",
    marginBottom: S[1] + 1,
  },
  dot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.teal400,
    marginTop: 4,
    marginRight: 7,
  },

  recRow: {
    flexDirection: "row",
    gap: S[3],
    paddingVertical: S[2] + 1,
    borderBottomWidth: 1,
    borderBottomColor: C.hair,
  },
  recNum: {
    width: 18,
    height: 18,
    borderRadius: R.md,
    backgroundColor: C.teal700,
    color: C.paper,
    fontSize: 9,
    fontWeight: 600,
    textAlign: "center",
    paddingTop: 3.5,
  },
  tag: {
    fontSize: 5.5,
    fontWeight: 600,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    borderWidth: 1,
    borderColor: C.hair,
    backgroundColor: C.paper2,
    color: C.ink500,
    borderRadius: R.sm,
    paddingVertical: 2,
    paddingHorizontal: 5,
    marginRight: 4,
  },

  footer: {
    position: "absolute",
    left: PAGE.margin,
    right: PAGE.margin,
    bottom: S[6],
  },
  footRule: {
    height: 2,
    backgroundColor: C.teal700,
    marginBottom: S[2],
  },
  footRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: T.micro,
    letterSpacing: 0.5,
    color: C.ink500,
    textTransform: "uppercase",
  },
  contsig: {
    fontSize: T.micro,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: C.ink300,
    marginBottom: S[4],
  },
  disc: {
    fontSize: T.small - 0.5,
    color: C.ink500,
    lineHeight: 1.5,
    borderTopWidth: 1,
    borderTopColor: C.hair,
    paddingTop: S[3],
    marginTop: S[3],
  },
});
